### ISSUE TITLE
Quick Play

### ISSUE THREAD

**Issue by BoogieHasFun** [Goobwabber/MultiQuestensions#10]
Quick Play does not work, it CFR-9's on expert+ and blacks out on expert.

**Comment by michael-r-elp** [comment]
Make sure you have BeatTogether installed and that it shows Modded Online, a CFR-9 can also mean that the server was down.
Also Expert+ and possibly Expert Quickplay lobbies generally tend to bug out currently, a server side fix is being worked on

**Comment by BoogieHasFun** [comment]
thanks ender

**Comment by cubicgraphics** [comment]
Should now be fixed on latest version. Also this would be a server/MpCore issue now
