### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by Lukeski7** [Goobwabber/MultiQuestensions#11]
cant even load a multiplayer game with my friend without crashing everytime i dont have chroma installed and it crahses everytime i start a custom song

**Comment by michael-r-elp** [comment]
Please get a log of the crash, you can get one using SideQuest for example, or get the tombstone file.

**Get tombstones for Beat Saber from the Quest**

1. Open SideQuest and goto `Manage files on the headset.`
2. Go to the following path `sdcard/Android/data/com.beatgames.beatsaber/files/` and there you should see your tombstones
3. Download them and attach them to this issue.


**How to get logs on SideQuest**

1. Click the Run ADB command button on the top right of SideQuest and click logcat
2. Choose an output folder and press start
3. Run the game with the Quest connected to your PC, and reproduce the problem you are experiencing wether that be a crash, or other mod failiure.
4. Once you're done with it, close SideQuest and send the log that just got generated by dragging and dropping it into discord.

**Comment by Lukeski7** [comment]
I sent everything to discord due to files not being able to attach
